---
- name: Deploy Info Page on all server 
  hosts: all
  become: yes
  vars:
    user_name: ravi

  tasks:
  - name: Copy Dynamic Page
    template:
      src: info.j2
      dest: /var/www/html/dynamic.html

...      